name: Publish

on:
  push:
    tags:        
      - v1.*

jobs:
  proxy-listing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Publish
      run: |
        echo ${GITHUB_REF##*/}
        GOPROXY=proxy.golang.org go list -m github.com/snirlugassy/lightdb@${GITHUB_REF##*/}
